function F = diagram( azimuth, elevation )
%DIAGRAM диаграмма направленности
    F = [ ...
            diagram_1(azimuth, elevation), ...
            diagram_2(azimuth, elevation), ...
            diagram_3(azimuth, elevation)
        ];
end