function diagram = diagram_s( azimuth, elevation )
%DIAGRAM_S парциальная диаграмма второго излучателя
    % азимутальная составляющая
    f2_a = exp(-1i*pi/4) * ...
        [ ...
            -sin(elevation); ...
            0; ...
            cos(azimuth) * cos(elevation) ...
        ];
    % в декартовых координатах
    f2_e = ...
        [ ...
            cos(elevation)^2                  * cos(azimuth) * sin(azimuth); ...
            cos(elevation)^2                  * sin(azimuth)^2 - 1; ...
            cos(elevation)   * sin(elevation) * sin(azimuth) ...
        ];
    % орты по углам
    [ ua, ue ] = units(azimuth, elevation);
    % парциальная диаграмма второго канала
    diagram = ...
        [ ...
            dot(f2_a, ua);
            dot(f2_a, ue)
        ] ...
        + ...
        [ ...
            dot(f2_e, ua);
            dot(f2_e, ue)
        ];
    % уменьшаем диаграмму
    diagram = 0.2 * diagram;
end