function result = diagram( azimuth, elevation, signals )
%DIAGRAM диаграмма направленности излучателя
    % парциальная диаграмма первого канала
    f1 = [ ...
            cos(elevation); ...
            0 ...
        ] * signals(1);

    % парциальная диаграмма второго канала в декартовых координатах
    f2_cartesian = [ ...
            cos(elevation)^2 * cos(azimuth) * sin(azimuth); ...
            cos(elevation)^2 * sin(azimuth)^2 - 1; ...
            cos(elevation) * sin(elevation) * sin(azimuth) ...
        ];
    % вычисляем орты по углам
    [ ua, ue ] = units(azimuth, elevation);
    % парциальная диаграмма второго канала
    f2 = [ ...
            dot(f2_cartesian, ue);
            dot(f2_cartesian, ua)
        ] * signals(2);

    result = [ f1, f2 ];
end

