function diagram = diagram_f( azimuth, elevation )
%DIAGRAM_F парциальная диаграмма первого излучателя
    diagram = 0.25 * [ ...
            cos(azimuth)*cos(elevation)*exp(1i*pi/3); ...
            cos(elevation) ...
        ];
end